# Generated by Django 5.1 on 2024-08-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.CharField(max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_usage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormAssur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situation', models.CharField(max_length=100)),
                ('banque', models.CharField(max_length=100)),
                ('accepter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MutuelleCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('accepter', models.BooleanField()),
            ],
        ),
    ]
